USE [master]
GO

/****** Object:  Database [ProjectManagement]    Script Date: 4/14/2019 2:24:02 AM ******/
CREATE DATABASE [ProjectManagement]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ProjectManagement', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\ProjectManagement.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'ProjectManagement_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\ProjectManagement_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [ProjectManagement] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ProjectManagement].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ProjectManagement] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ProjectManagement] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ProjectManagement] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ProjectManagement] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ProjectManagement] SET ARITHABORT OFF 
GO

ALTER DATABASE [ProjectManagement] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ProjectManagement] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [ProjectManagement] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ProjectManagement] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ProjectManagement] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ProjectManagement] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ProjectManagement] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ProjectManagement] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ProjectManagement] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ProjectManagement] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ProjectManagement] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ProjectManagement] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ProjectManagement] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ProjectManagement] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ProjectManagement] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ProjectManagement] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ProjectManagement] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ProjectManagement] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ProjectManagement] SET RECOVERY FULL 
GO

ALTER DATABASE [ProjectManagement] SET  MULTI_USER 
GO

ALTER DATABASE [ProjectManagement] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ProjectManagement] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ProjectManagement] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ProjectManagement] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [ProjectManagement] SET  READ_WRITE 
GO


